# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import llm_pb2 as llm__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LlmStub(object):
    """============================================================================
    СЕРВИС И RPC-МЕТОДЫ
    ============================================================================

    Service определяет API сервиса - набор удаленных процедур (RPC), которые можно вызвать.
    Это аналог интерфейса в программировании.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/llm.Llm/Ping',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.NewMessage = channel.unary_stream(
                '/llm.Llm/NewMessage',
                request_serializer=llm__pb2.NewMessageRequest.SerializeToString,
                response_deserializer=llm__pb2.NewMessageResponse.FromString,
                _registered_method=True)
        self.Transcribe = channel.stream_unary(
                '/llm.Llm/Transcribe',
                request_serializer=llm__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=llm__pb2.TranscribeResponse.FromString,
                _registered_method=True)
        self.AvailableModelsText2Text = channel.unary_unary(
                '/llm.Llm/AvailableModelsText2Text',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=llm__pb2.StringsListResponse.FromString,
                _registered_method=True)
        self.AvailableModelsSpeech2Text = channel.unary_unary(
                '/llm.Llm/AvailableModelsSpeech2Text',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=llm__pb2.StringsListResponse.FromString,
                _registered_method=True)
        self.AvailableTools = channel.unary_unary(
                '/llm.Llm/AvailableTools',
                request_serializer=llm__pb2.AvailableToolsRequest.SerializeToString,
                response_deserializer=llm__pb2.StringsListResponse.FromString,
                _registered_method=True)


class LlmServicer(object):
    """============================================================================
    СЕРВИС И RPC-МЕТОДЫ
    ============================================================================

    Service определяет API сервиса - набор удаленных процедур (RPC), которые можно вызвать.
    Это аналог интерфейса в программировании.
    """

    def Ping(self, request, context):
        """Ping - простой метод для проверки работоспособности сервиса.
        Принимает: пустой объект (Empty)
        Возвращает: пустой объект (Empty)
        Используется для health-check'ов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewMessage(self, request, context):
        """NewMessage - метод для отправки сообщения языковой модели и получения ответа.
        Принимает: одиночный NewMessageRequest.
        Возвращает: поток (stream) из NewMessageResponse — сервер будет отправлять
        промежуточные части генерации и финальную статистику по мере готовности.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transcribe(self, request_iterator, context):
        """Transcribe - метод для отправки только аудио и получения транскрипции без генерации
        Принимает: поток TranscribeRequest с mp3_chunk
        Возвращает: одиночный TranscribeResponse с результатом транскрибации
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AvailableModelsText2Text(self, request, context):
        """AvailableModelsText2Text - получить список доступных Text2Text моделей.
        Принимает: пустой объект (Empty)
        Возвращает: StringsListResponse со списком моделей
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AvailableModelsSpeech2Text(self, request, context):
        """AvailableModelsSpeech2Text - получить список доступных Speech2Text моделей.
        Принимает: пустой объект (Empty)
        Возвращает: StringsListResponse со списком моделей
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AvailableTools(self, request, context):
        """AvailableTools - получить список доступных инструментов/функций.
        Принимает: пустой объект (Empty)
        Возвращает: StringsListResponse со списком названий инструментов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlmServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'NewMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.NewMessage,
                    request_deserializer=llm__pb2.NewMessageRequest.FromString,
                    response_serializer=llm__pb2.NewMessageResponse.SerializeToString,
            ),
            'Transcribe': grpc.stream_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=llm__pb2.TranscribeRequest.FromString,
                    response_serializer=llm__pb2.TranscribeResponse.SerializeToString,
            ),
            'AvailableModelsText2Text': grpc.unary_unary_rpc_method_handler(
                    servicer.AvailableModelsText2Text,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=llm__pb2.StringsListResponse.SerializeToString,
            ),
            'AvailableModelsSpeech2Text': grpc.unary_unary_rpc_method_handler(
                    servicer.AvailableModelsSpeech2Text,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=llm__pb2.StringsListResponse.SerializeToString,
            ),
            'AvailableTools': grpc.unary_unary_rpc_method_handler(
                    servicer.AvailableTools,
                    request_deserializer=llm__pb2.AvailableToolsRequest.FromString,
                    response_serializer=llm__pb2.StringsListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm.Llm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llm.Llm', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Llm(object):
    """============================================================================
    СЕРВИС И RPC-МЕТОДЫ
    ============================================================================

    Service определяет API сервиса - набор удаленных процедур (RPC), которые можно вызвать.
    Это аналог интерфейса в программировании.
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.Llm/Ping',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NewMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/llm.Llm/NewMessage',
            llm__pb2.NewMessageRequest.SerializeToString,
            llm__pb2.NewMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transcribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/llm.Llm/Transcribe',
            llm__pb2.TranscribeRequest.SerializeToString,
            llm__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AvailableModelsText2Text(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.Llm/AvailableModelsText2Text',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            llm__pb2.StringsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AvailableModelsSpeech2Text(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.Llm/AvailableModelsSpeech2Text',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            llm__pb2.StringsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AvailableTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.Llm/AvailableTools',
            llm__pb2.AvailableToolsRequest.SerializeToString,
            llm__pb2.StringsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
